/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as ProductsAllRouteImport } from './routes/products/all'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as AdminDeleteProductRouteImport } from './routes/admin/delete-product'
import { Route as AdminCreateProductRouteImport } from './routes/admin/create-product'

const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAllRoute = ProductsAllRouteImport.update({
  id: '/products/all',
  path: '/products/all',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDeleteProductRoute = AdminDeleteProductRouteImport.update({
  id: '/admin/delete-product',
  path: '/admin/delete-product',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreateProductRoute = AdminCreateProductRouteImport.update({
  id: '/admin/create-product',
  path: '/admin/create-product',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/admin/create-product': typeof AdminCreateProductRoute
  '/admin/delete-product': typeof AdminDeleteProductRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/all': typeof ProductsAllRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/cart/': typeof CartIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/admin/create-product': typeof AdminCreateProductRoute
  '/admin/delete-product': typeof AdminDeleteProductRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/all': typeof ProductsAllRoute
  '/about': typeof AboutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/cart': typeof CartIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin/create-product': typeof AdminCreateProductRoute
  '/admin/delete-product': typeof AdminDeleteProductRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/all': typeof ProductsAllRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/cart/': typeof CartIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin/create-product'
    | '/admin/delete-product'
    | '/products/$productId'
    | '/products/all'
    | '/about/'
    | '/admin/'
    | '/cart/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin/create-product'
    | '/admin/delete-product'
    | '/products/$productId'
    | '/products/all'
    | '/about'
    | '/admin'
    | '/cart'
    | '/products'
  id:
    | '__root__'
    | '/admin/create-product'
    | '/admin/delete-product'
    | '/products/$productId'
    | '/products/all'
    | '/about/'
    | '/admin/'
    | '/cart/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminCreateProductRoute: typeof AdminCreateProductRoute
  AdminDeleteProductRoute: typeof AdminDeleteProductRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsAllRoute: typeof ProductsAllRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CartIndexRoute: typeof CartIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/all': {
      id: '/products/all'
      path: '/products/all'
      fullPath: '/products/all'
      preLoaderRoute: typeof ProductsAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/delete-product': {
      id: '/admin/delete-product'
      path: '/admin/delete-product'
      fullPath: '/admin/delete-product'
      preLoaderRoute: typeof AdminDeleteProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create-product': {
      id: '/admin/create-product'
      path: '/admin/create-product'
      fullPath: '/admin/create-product'
      preLoaderRoute: typeof AdminCreateProductRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AdminCreateProductRoute: AdminCreateProductRoute,
  AdminDeleteProductRoute: AdminDeleteProductRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsAllRoute: ProductsAllRoute,
  AboutIndexRoute: AboutIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  CartIndexRoute: CartIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
